run:
  timeout: 5m
linters:
  enable:
  - gofmt
  - misspell
  - revive
issues:
  exclude-rules:
  - linters:
    - structcheck
    - unused
    text: "`data` is unused"
  - linters:
    - staticcheck
    text: "SA1019:"
  - linters:
    - revive
    text: "var-naming:"
  - linters:
    - revive
    text: "exported:"
